spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev

  datasource:
    url: jdbc:oracle:thin:@DB202203301935_medium?TNS_ADMIN=./key
    driverClassName: oracle.jdbc.OracleDriver
    username: ADMIN
    password: BDrelacional5
  
  jpa:
    open-in-view: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: true

---

spring:
  config:
    activate:
      on-profile: prod

  datasource:
    url: jdbc:oracle:thin:@DB202203301935_medium?TNS_ADMIN=./key
    driverClassName: oracle.jdbc.OracleDriver
    username: ADMIN
    password: BDrelacional5
  
  jpa:
    open-in-view: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.Oracle12cDialect
        format_sql: false