package api.theVelopers.sas.service.impl;// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;

import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.JavascriptExecutor;

import java.util.*;

public class TesteIntegracao {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void teste2() throws InterruptedException {
    driver.get("https://score-analysis-system-front.herokuapp.com/#/");
    driver.manage().window().setSize(new Dimension(1360, 768));
    {
      WebElement element = driver.findElement(By.xpath("//*[@id=\"app\"]/div[1]/header/div/div[5]/div[2]/a/span"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element).perform();
    }
    Thread.sleep(5000);
    driver.findElement(By.xpath("//*[@id=\"app\"]/div[1]/header/div/div[5]/div[2]/a/span")).click();
    {
      WebElement element = driver.findElement(By.tagName("body"));
      Actions builder = new Actions(driver);
      builder.moveToElement(element, 0, 0).perform();
    }
    Thread.sleep(5000);
  }
}
