name: CI 

on:
    push:
        branches: [ dev ]

jobs:

  build_and_test:
  #aqui é em que máquina os passos devem ser executados
    runs-on: ubuntu-latest
    # passos
    steps:
        # nome do passo
      - name: Step 1 - checkout
        # uso de actions do github
        uses: actions/checkout@v2

      - name: Step 2 - set up JDK 11
        uses: actions/setup-java@v1
        with:
            # informando o actions do github qual o jdk
          java-version: 11
      
      - name: Step 3- cache Maven packages
        uses: actions/cache@v1
        # informando o actions do github para guardar os packages no m2 que é o repo do maven na máquina
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2  
          
      - name: Step 4 - build and test
        # aqui é onde roda o comando package do maven, ele testa e faz o pacote para deploy
        run: mvn -B package --file pom.xml
    
      
      # Runs a set of commands using the runners shell
      - name: Step 5 - list current dir
        # aqui é onde ele lista o diretório da máquina
        run: ls -a
