name: CI/CD

on:
    push:
        branches: [ main ]

jobs:
  clean_build_deploy:
  
    runs-on: ubuntu-latest

    steps:
      - name: Step 1 - checkout
        uses: actions/checkout@v2

      - name: Step 2 - set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Step 3 - cache local Maven repository
        uses: actions/cache@v3
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
                        ${{ runner.os }}-maven-  
      
      - name: Step 4 - change to prod
        run: sed -i 's/dev/prod/' src/main/resources/application.yml
      
      - name: Step 5 - install google chrome
        run: |
          chmod +x ./scripts/InstallChrome.sh
           ./scripts/InstallChrome.sh
        
      - name: Step 6 - integration test
        run: mvn -Dtest="theVelopers.sas.integration.**" test
      
      - name: Step 7 - clean and build
        run: mvn -B -DskipTests clean package
    
      - name: Step 8 - move jar to staging dir
        run: mkdir staging && cp target/*.jar staging
      
      - name: Step 9 - set jar to download
        uses: actions/upload-artifact@v2
        with:
          name: sas-artifact
          path: staging
        
      - name: Step 10 - deploy heroku
        uses: akhileshns/heroku-deploy@v3.12.12
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "score-analysis-system-back"
          heroku_email: "score.analysis.sytem@gmail.com"
