name: CI Main

on:
    push:
        branches: [ main ]

jobs:
  clean_build_deploy:
  
    runs-on: ubuntu-latest

    # Setando o ambiente
    environment:
      name: main

    steps:
      - name: Step 1 - checkout
        uses: actions/checkout@v2

      - name: Step 2 - set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
      
      - name: Step 3 - cache local Maven repository
        uses: actions/cache@v3
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: |
                        ${{ runner.os }}-maven-  
      
      - name: Step 4 - change to prod
        run: sed -i 's/dev/prod/' src/main/resources/application.yml
      
      - name: Step 5 - clean and build
        run: mvn -B -DskipTests clean package
    
      - name: Step 6 - build and push docker image
        uses: mr-smithers-excellent/docker-build-push@v4
        with:
            image: jef771/sas-app
            registry: docker.io
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}